### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by EndLess728** [Emurgo/react-native-cardano#15]
I have installed this lib and when I tried to install it gave me some errors related to linking . To fix linking errors i manually setup the project according to the instructions but now i am facing new error .

```
~/Desktop/demo_tests/cardanoSample » npx react-native run-android                                                                                     ios@ios
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 905 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ios/Desktop/demo_tests/cardanoSample/node_modules/react-native-cardano/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':react-native-cardano'.
> Plugin with id 'org.mozilla.rust-android-gradle.rust-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-cardano'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/ios/Desktop/demo_tests/cardanoSample/node_modules/react-native-cardano/android/build.gradle' line: 21

* What went wrong:
A problem occurred evaluating project ':react-native-cardano'.
> Plugin with id 'org.mozilla.rust-android-gradle.rust-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-cardano'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (/Users/ios/Desktop/demo_tests/cardanoSample/node_modules/execa/index.js:174:9)
    at /Users/ios/Desktop/demo_tests/cardanoSample/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/ios/Desktop/demo_tests/cardanoSample/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
    at async Command.handleAction (/Users/ios/Desktop/demo_tests/cardanoSample/node_modules/@react-native-community/cli/build/index.js:186:9)
info Run CLI with --verbose flag for more details.
```

**Comment by v-almonacid** [comment]
Hi @EndLess728, in your root `build.gradle`, you need to add `rust-android-gradle` as a dependency in your `buildscript`, it should be something like:

```
repositories {
        ...
        // rust-android-gradle
        maven {
            url "https://plugins.gradle.org/m2/"
            google()
        }
    }
    dependencies {
        ...
        classpath 'gradle.plugin.org.mozilla.rust-android-gradle:plugin:0.8.3'
    }
 ```
 
 Also, keep in mind that this library is outdated and only includes Byron-era funcionality. I don't think Emurgo will continue maintaining it.
